products.insertMany([   
  
    {
        product__name: "TERMO",
        product__nameFilter: "1",
        product__colour: "salmon",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoP1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",        
    },

    {
        product__name: "TERMO",
        product__nameFilter: "2",
        product__colour: "salmon",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoP2.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__nameFilter: "3",
        product__colour: "salmon",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoP3.png",
        product__price: "19.95",
        product__size: "9 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",           
    },

    {
        product__name: "TERMO",
        product__nameFilter: "4",
        product__colour: "salmon",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoP4.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.", 
        product__Type: "filterTwo",          
    },

    {
        product__name: "TERMO",
        product__nameFilter: "5",
        product__colour: "salmon",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoP5.png",
        product__price: "19.95",
        product__size: "9 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",           
    },

    {
        product__name: "TERMO",
        product__nameFilter: "6",
        product__colour: "salmon",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoP6.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__nameFilter: "7",
        product__colour: "salmon",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoP7.png",
        product__price: "19.95",
        product__size: "9 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__nameFilter: "8",
        product__colour: "azul",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoA1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.", 
        product__Type: "filterTwo",           
    },

    {
        product__name: "TERMO",
        product__nameFilter: "9",
        product__colour: "azul",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoA2.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__nameFilter: "10",
        product__colour: "azul",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoA3.png",
        product__price: "19.95",
        product__size: "9 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.", 
        product__Type: "filterTwo",           
    },

    {
        product__name: "TERMO",
        product__nameFilter: "11",
        product__colour: "azul",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoA4.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__nameFilter: "12",
        product__colour: "azul",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoA5.png",
        product__price: "19.95",
        product__size: "9 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",           
    },

    {
        product__name: "TERMO",
        product__nameFilter: "13",
        product__colour: "blanco",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoB1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.", 
        product__Type: "filterTwo",          
    },

    {
        product__name: "TERMO",
        product__nameFilter: "14",
        product__colour: "blanco",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoB2.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__nameFilter: "15",
        product__colour: "blanco",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoB3.png",
        product__price: "19.95",
        product__size: "9 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",  
        product__Type: "filterTwo",          
    },

    {
        product__name: "TERMO",
        product__nameFilter: "16",
        product__colour: "verde",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoG1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",           
    },

    {
        product__name: "TERMO",
        product__nameFilter: "17",
        product__colour: "verde",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoG2.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__nameFilter: "18",
        product__colour: "verde",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoG3.png",
        product__price: "19.95",
        product__size: "9 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__nameFilter: "19",
        product__colour: "verde",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoG4.png",
        product__price: "19.95",
        product__size: "9 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__nameFilter: "20",
        product__colour: "negro",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoN1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",           
    },

    {
        product__name: "TERMO",
        product__nameFilter: "21",
        product__colour: "negro",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoN2.png",
        product__price: "19.95",
        product__size: "9 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.", 
        product__Type: "filterTwo",           
    },

    {
        product__name: "TERMO",
        product__nameFilter: "22",
        product__colour: "negro",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoN3.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__nameFilter: "23",
        product__colour: "negro",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoN4.png",
        product__price: "19.95",
        product__size: "9 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__nameFilter: "24",
        product__colour: "rosado",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoQ1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",    

    },

    {
        product__name: "TERMO",
        product__nameFilter: "25",
        product__colour: "rosado",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoQ2.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__nameFilter: "26",
        product__colour: "rosado",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoQ3.png",
        product__price: "19.95",
        product__size: "9 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",           
    },

    {
        product__name: "TERMO",
        product__nameFilter: "27",
        product__colour: "rosado",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoR1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__nameFilter: "28",
        product__colour: "rosado",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoR2.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "rosado",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoR3.png",
        product__price: "19.95",
        product__size: "9 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",           
    },

    {
        product__name: "TERMO",
        product__colour: "turqueza",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoT1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "turqueza",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoT2.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "turqueza",
        product__collectio:"CLASICO",
        product__img: "/imagenesTienda/Products/TermosClasicos/termoT3.png",
        product__price: "19.95",
        product__size: "9 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "azul",
        product__collectio:"GIMNASIO",
        product__img: "/imagenesTienda/Products/Gimnasio/azul1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Termo jaspeada inspirada en ropa deportiva. Ajuste para su entrenamiento favorito. Disponible en tres colores energéticos con un acabado mate estampado y una tapa roscada a juego. Disfrute de su bebida fría o caliente favorita, en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "azul",
        product__collectio:"GIMNASIO",
        product__img: "/imagenesTienda/Products/Gimnasio/azul2.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Termo jaspeada inspirada en ropa deportiva. Ajuste para su entrenamiento favorito. Disponible en tres colores energéticos con un acabado mate estampado y una tapa roscada a juego. Disfrute de su bebida fría o caliente favorita, en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "rosado",
        product__collectio:"GIMNASIO",
        product__img: "/imagenesTienda/Products/Gimnasio/rosa1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Termo jaspeada inspirada en ropa deportiva. Ajuste para su entrenamiento favorito. Disponible en tres colores energéticos con un acabado mate estampado y una tapa roscada a juego. Disfrute de su bebida fría o caliente favorita, en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "rosado",
        product__collectio:"GIMNASIO",
        product__img: "/imagenesTienda/Products/Gimnasio/rosa2.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Termo jaspeada inspirada en ropa deportiva. Ajuste para su entrenamiento favorito. Disponible en tres colores energéticos con un acabado mate estampado y una tapa roscada a juego. Disfrute de su bebida fría o caliente favorita, en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "cafe",
        product__collectio:"METALICO",
        product__img: "/imagenesTienda/Products/Metalico/cafe1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: " Deshazte de la nevera. Mantener la calma Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "cafe",
        product__collectio:"METALICO",
        product__img: "/imagenesTienda/Products/Metalico/cafe2.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: " Deshazte de la nevera. Mantener la calma Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "negro",
        product__collectio:"METALICO",
        product__img: "/imagenesTienda/Products/Metalico/negro1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: " Deshazte de la nevera. Mantener la calma Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "negro",
        product__collectio:"METALICO",
        product__img: "/imagenesTienda/Products/Metalico/negro2.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: " Deshazte de la nevera. Mantener la calma Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "rosado",
        product__collectio:"METALICO",
        product__img: "/imagenesTienda/Products/Metalico/rosa1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: " Deshazte de la nevera. Mantener la calma Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "rosado",
        product__collectio:"METALICO",
        product__img: "/imagenesTienda/Products/Metalico/rosa2.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: " Deshazte de la nevera. Mantener la calma Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "gris",
        product__collectio:"METALICO",
        product__img: "/imagenesTienda/Products/Metalico/gris1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: " Deshazte de la nevera. Mantener la calma Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "gris",
        product__collectio:"METALICO",
        product__img: "/imagenesTienda/Products/Metalico/gris2.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: " Deshazte de la nevera. Mantener la calma Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "gris",
        product__collectio:"METALICO",
        product__img: "/imagenesTienda/Products/Metalico/gris3.png",
        product__price: "19.95",
        product__size: "9 OZ",
        product__description: " Deshazte de la nevera. Mantener la calma Disfrute de su bebida favorita fría o caliente en cualquier momento y en cualquier lugar. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "azul",
        product__collectio:"SURF",
        product__img: "/imagenesTienda/Products/Surf/azul1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Si el agua es profunda, si es parte de lo que eres, entonces eres un Waterman. La misma cantina que le encanta en nuestro acabado texturizado con recubrimiento en polvo. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "azul",
        product__collectio:"SURF",
        product__img: "/imagenesTienda/Products/Surf/azul2.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Si el agua es profunda, si es parte de lo que eres, entonces eres un Waterman. La misma cantina que le encanta en nuestro acabado texturizado con recubrimiento en polvo. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",             
    },

    {
        product__name: "TERMO",
        product__colour: "azul",
        product__collectio:"SURF",
        product__img: "/imagenesTienda/Products/Surf/azul3.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Si el agua es profunda, si es parte de lo que eres, entonces eres un Waterman. La misma cantina que le encanta en nuestro acabado texturizado con recubrimiento en polvo. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "azul",
        product__collectio:"SURF",
        product__img: "/imagenesTienda/Products/Surf/azul4.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Si el agua es profunda, si es parte de lo que eres, entonces eres un Waterman. La misma cantina que le encanta en nuestro acabado texturizado con recubrimiento en polvo. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",             
    },

    {
        product__name: "TERMO",
        product__colour: "negro",
        product__collectio:"SURF",
        product__img: "/imagenesTienda/Products/Surf/negro1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Si el agua es profunda, si es parte de lo que eres, entonces eres un Waterman. La misma cantina que le encanta en nuestro acabado texturizado con recubrimiento en polvo. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "negro",
        product__collectio:"SURF",
        product__img: "/imagenesTienda/Products/Surf/negro2.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Si el agua es profunda, si es parte de lo que eres, entonces eres un Waterman. La misma cantina que le encanta en nuestro acabado texturizado con recubrimiento en polvo. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",             
    },

    {
        product__name: "TERMO",
        product__colour: "negro",
        product__collectio:"SURF",
        product__img: "/imagenesTienda/Products/Surf/negro4.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Si el agua es profunda, si es parte de lo que eres, entonces eres un Waterman. La misma cantina que le encanta en nuestro acabado texturizado con recubrimiento en polvo. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },
    
    {
        product__name: "TERMO",
        product__colour: "negro",
        product__collectio:"SURF",
        product__img: "/imagenesTienda/Products/Surf/negro5.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Si el agua es profunda, si es parte de lo que eres, entonces eres un Waterman. La misma cantina que le encanta en nuestro acabado texturizado con recubrimiento en polvo. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",             
    },

    {
        product__name: "TERMO",
        product__colour: "rosado",
        product__collectio:"SURF",
        product__img: "/imagenesTienda/Products/Surf/rojo1.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Si el agua es profunda, si es parte de lo que eres, entonces eres un Waterman. La misma cantina que le encanta en nuestro acabado texturizado con recubrimiento en polvo. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",             
    },

    {
        product__name: "TERMO",
        product__colour: "rosado",
        product__collectio:"SURF",
        product__img: "/imagenesTienda/Products/Surf/rojo2.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Si el agua es profunda, si es parte de lo que eres, entonces eres un Waterman. La misma cantina que le encanta en nuestro acabado texturizado con recubrimiento en polvo. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "rosado",
        product__collectio:"SURF",
        product__img: "/imagenesTienda/Products/Surf/rosa1.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Si el agua es profunda, si es parte de lo que eres, entonces eres un Waterman. La misma cantina que le encanta en nuestro acabado texturizado con recubrimiento en polvo. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",             
    },

    {
        product__name: "TERMO",
        product__colour: "rosado",
        product__collectio:"SURF",
        product__img: "/imagenesTienda/Products/Surf/rosa2.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Si el agua es profunda, si es parte de lo que eres, entonces eres un Waterman. La misma cantina que le encanta en nuestro acabado texturizado con recubrimiento en polvo. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "verde",
        product__collectio:"SURF",
        product__img: "/imagenesTienda/Products/Surf/verde1.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Si el agua es profunda, si es parte de lo que eres, entonces eres un Waterman. La misma cantina que le encanta en nuestro acabado texturizado con recubrimiento en polvo. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    {
        product__name: "TERMO",
        product__colour: "verde",
        product__collectio:"SURF",
        product__img: "/imagenesTienda/Products/Surf/verde2.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Si el agua es profunda, si es parte de lo que eres, entonces eres un Waterman. La misma cantina que le encanta en nuestro acabado texturizado con recubrimiento en polvo. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",             
    },

    {
        product__name: "TERMO",
        product__colour: "verde",
        product__collectio:"SURF",
        product__img: "/imagenesTienda/Products/Surf/verde3.png",
        product__price: "32.95",
        product__size: "25 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Si el agua es profunda, si es parte de lo que eres, entonces eres un Waterman. La misma cantina que le encanta en nuestro acabado texturizado con recubrimiento en polvo. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",            
    },

    
    {
        product__name: "TERMO",
        product__colour: "verde",
        product__collectio:"SURF",
        product__img: "/imagenesTienda/Products/Surf/verde4.png",
        product__price: "27.95",
        product__size: "16 OZ",
        product__description: "Deshazte de la nevera. Mantener la calma. Si el agua es profunda, si es parte de lo que eres, entonces eres un Waterman. La misma cantina que le encanta en nuestro acabado texturizado con recubrimiento en polvo. Fabricado en acero inoxidable con triple aislamiento patentado. Mantiene las bebidas frías con hielo por hasta 25 horas o caliente por hasta 12 horas sin congelarse o sudar. Frío aún más tiempo para bebidas que contengan hielo.",
        product__characteristics: "Antideslizante, fondo de silicona.Laterales de fácil agarre.Tapón de rosca.",
        product__Type: "filterTwo",             
    },

   
]);


